[tool.poetry]
name = "brick-games"
version = "0.1.0"
description = "A library of simple brick games using the raylib library."
authors = [
  "Mauricio <mg4145@columbia.edu>",
  "Eridani <ealcantar@utexas.edu>",
  ]
readme = "README.md"
packages = [{include = "brick_games", from = "src"},
            {include = "games", from = "src/brick_games"}]


[tool.poetry.dependencies]
python = "^3.11"
raylib = "^5.0.0.1"
numpy = "^1.26.4"


[tool.poetry.group.dev.dependencies]
pynvim = "^0.5.0"
pytest = "^8.0.2"
setuptools = "^69.1.1"
black = "^24.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# [tool.poetry.scripts]
# greet = "bricks.main:greet"
# hi = "bricks.main:hi"
